name: Daily Scholarship Scraper

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 7:30 AM IST
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requirements
      run: |
        pip install requests beautifulsoup4

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push if changed
      run: |
        git config --global user.name "OneClick Bot"
        git config --global user.email "bot@oneclick.com"
        git add scholarships.json
        git diff --cached --quiet || git commit -m "🔄 Auto update scholarships"
        git push
